# Generated by Django 3.2.7 on 2021-09-21 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField()),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('cont', models.TextField()),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
