# Generated by Django 3.2.7 on 2021-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='shortthumb',
            field=models.TextField(default='null'),
        ),
    ]
