# Generated by Django 3.2.7 on 2021-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210928_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='heading',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='content',
            name='subhead',
            field=models.TextField(blank=True),
        ),
    ]
