# Generated by Django 3.2.7 on 2021-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20210930_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.BinaryField(blank=True),
        ),
    ]
