# Generated by Django 3.2.7 on 2021-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.BinaryField(),
        ),
    ]
