# Generated by Django 3.2.7 on 2021-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
