# Generated by Django 3.2.7 on 2021-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_content_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
    ]
